package it.exercise.TestUnit.entities;

import jakarta.persistence.*;

/**
 * @author Drumstyle92
 * Class represents the entity that maps to the users table in the database
 */
@Entity
@Table(name = "users")
public class UserEntity {

    /**
     * Variable that represents the id of the row in
     * the users table and is automatically generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Variable representing the name in the user table column
     */
    @Column(name = "first_name")
    private String firstName;

    /**
     * Variable representing the surname in the user table column
     */
    @Column(name = "last_name")
    private String lastName;

    /**
     * Variable representing the email in the user table column
     */
    @Column(name = "email")
    private String email;

    /**
     * Default constructor
     */
    public UserEntity(){}

    /**

     * @param id        the id
     * @param firstName the first name
     * @param lastName  the last name
     * @param email     the email
     * Parameterized constructor
     */
    public UserEntity(Long id, String firstName, String lastName, String email) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    /**
     * @return the id
     * Method for encapsulation
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id
     * Method for encapsulation
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the first name
     * Method for encapsulation
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * @param firstName the first name
     * Method for encapsulation
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return the last name
     * Method for encapsulation
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @param lastName the last name
     * Method for encapsulation
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return the email
     * Method for encapsulation
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email the email
     * Method for encapsulation
     */
    public void setEmail(String email) {
        this.email = email;
    }

}
